// /data/ProjectGalleries.js

const ProjectGalleries = {
    Lokal: [
        "/images/lokal/Admin%20-%20Designers%204%20(view%20products).png",
        "/images/lokal/Login.png",
        "/images/lokal/Designer%20-%20Add%20Product%20(Clothing).png",
        "/images/lokal/Super%20Admin%20-%20Orders%205.png",
        "/images/lokal/Super%20Admin%20-%20Orders%204.png",
        "/images/lokal/Admin%20-%20Designers%202%20(add).png",
        "/images/lokal/Super%20Admin%20-%20Orders%201.png",
        "/images/lokal/Become%20a%20Lokal%20Vendor%201.png",
        "/images/lokal/Super%20Admin%20-%20Orders%203.png",
        "/images/lokal/Super%20Admin%20-%20Orders%202.png",
        "/images/lokal/Admin%20-%20Finance%202.png",
        "/images/lokal/Super%20Admin%20-%20Create%20Order%201.png",
        "/images/lokal/Designer%20-%20Add%20Product%20(Home%20&%20Gifts).png",
        "/images/lokal/Designer%20-%20Business%20Settings%201.png",
        "/images/lokal/Admin%20-%20Designers%201.png",
        "/images/lokal/Admin%20-%20Pending%20Approval.png",
        "/images/lokal/Designer%20-%20Products.png"
    ],

    MyStartCloud: [
        "/images/mystartcloud/Icons%20Library.png",
        "/images/mystartcloud/New%20Collection%20-%20Custom%20Apps%202.png",
        "/images/mystartcloud/Social%20media%20feed.png",
        "/images/mystartcloud/SP%20-%20Forgot%20Password.png",
        "/images/mystartcloud/Users.png",
        "/images/mystartcloud/School%20Settings.png",
        "/images/mystartcloud/Collections%20-%20Edit%20App.png",
        "/images/mystartcloud/New%20Collection%20-%20Details.png",
        "/images/mystartcloud/SP%20-%20Private%20-%20Login.png",
        "/images/mystartcloud/New%20Collection%20-%20Cloud%20Apps%201.png",
        "/images/mystartcloud/Announcement.png",
        "/images/mystartcloud/New%20Collection%20-%20Cloud%20Apps%202.png",
        "/images/mystartcloud/Collections%20-%20Edit%20Group.png",
        "/images/mystartcloud/Collections.png",
        "/images/mystartcloud/1440px%20-%20Home.png",
        "/images/mystartcloud/Registerations%201.png",
        "/images/mystartcloud/1440px%20-%20Note%20Fullscreen.png",
        "/images/mystartcloud/Billing.png",
    ],

    NaseebiMobile: [
        "/images/naseebimobile/Create%202b.png",
        "/images/naseebimobile/Sign%20in.png",
        "/images/naseebimobile/Your%20Avatar.png",
        "/images/naseebimobile/Settings.png",
        "/images/naseebimobile/Pricing.png",
        "/images/naseebimobile/Match%20Profile%20-%20Free.png",
        "/images/naseebimobile/Match%20Profile_Not%20for%20me%202.png",
        "/images/naseebimobile/Create%206.png",
        "/images/naseebimobile/Create%207.png",
        "/images/naseebimobile/Create%201.png",
        "/images/naseebimobile/Complete%20profile.png",
        "/images/naseebimobile/Tour%202.png",
        "/images/naseebimobile/Chat%204.png",
        "/images/naseebimobile/Your%20Connections%201.png",
        "/images/naseebimobile/Tour%203.png",
        "/images/naseebimobile/Your%20Connections%203.png",
        "/images/naseebimobile/Match%20Profile%20-%20Paid,%20Connected.png",
        "/images/naseebimobile/Coming%20Soon.png",
        "/images/naseebimobile/Chat%202.png",
        "/images/naseebimobile/Chat%201.png",
        "/images/naseebimobile/Match%20Profile%20-%20Connect%20Popup.png",
        "/images/naseebimobile/Your%20profile%202.png",
        "/images/naseebimobile/My%20Profile%201.png",
        "/images/naseebimobile/Home_Loading_Male.png",
        "/images/naseebimobile/Your%20profile%201.png",
        "/images/naseebimobile/Preferences%206.png",
        "/images/naseebimobile/Home%201.png",
        "/images/naseebimobile/Need%20more%20time.png",
        "/images/naseebimobile/Your%20Profile_Add%20photos.png"
    ],

    Cazasouq: [
        "/images/cazasouq/Wishlist.png",
        "/images/cazasouq/Checkout%20-%20Address.png",
        "/images/cazasouq/Products%20List%20-%20Product%20Details%202.png",
        "/images/cazasouq/Search%20-%20Clicked.png",
        "/images/cazasouq/Checkout%20-%20Finished.png",
        "/images/cazasouq/Onboarding%201.png",
        "/images/cazasouq/Products%20List%20-%20Product%20Details%201.png",
        "/images/cazasouq/Currencies.png",
        "/images/cazasouq/Settings.png",
        "/images/cazasouq/Settings%20After%20Login.png",
        "/images/cazasouq/Checkout%20-%20Payment.png",
        "/images/cazasouq/Login%20or%20Create%20Account.png",
        "/images/cazasouq/Checkout%20-%20Preview.png",
        "/images/cazasouq/View%20your%20order%20history.png",
        "/images/cazasouq/Checkout%20-%20Shipping.png",
        "/images/cazasouq/Splash.png",
        "/images/cazasouq/Menu.png",
        "/images/cazasouq/Menu%20Open.png",
        "/images/cazasouq/Currency.png",
        "/images/cazasouq/Products%20List.png",
        "/images/cazasouq/Categories.png",
        "/images/cazasouq/Order%20Details%204.png",
        "/images/cazasouq/Search%20Results.png",
        "/images/cazasouq/Reset%20Password%202.png",
        "/images/cazasouq/Order%20Details%201.png",
        "/images/cazasouq/Order%20Details%202.png"
    ],

    Chillupwebdashboard: [
        "/images/chillupwebdashboard/Products%201.png",
        "/images/chillupwebdashboard/Transactions.png",
        "/images/chillupwebdashboard/Follows%20&%20Reviews.png",
        "/images/chillupwebdashboard/vendor%20register%202.png",
        "/images/chillupwebdashboard/Create_%20New%20Class%205%20(Fixed%20Terms).png",
        "/images/chillupwebdashboard/Account%203_My%20Profile.png",
        "/images/chillupwebdashboard/Products%202%20-%20View%20Product%20(Slots).png",
        "/images/chillupwebdashboard/vendor%20register%201.png",
        "/images/chillupwebdashboard/Account%204.png",
        "/images/chillupwebdashboard/Create_%20New%20Class%204%20(Fixed%20Terms).png",
        "/images/chillupwebdashboard/Customer%20List%201.png",
        "/images/chillupwebdashboard/Account%206_Plan%20Super%20Chill.png",
        "/images/chillupwebdashboard/Customer%20List%202.png",
        "/images/chillupwebdashboard/Account2.png",
        "/images/chillupwebdashboard/Create_%20New%20Class%205%20(Period).png",
        "/images/chillupwebdashboard/Bookings%201.png",
        "/images/chillupwebdashboard/Customer%20List_Free%20Plan.png",
        "/images/chillupwebdashboard/Create_%20New%20Class%204%20(Period).png",
        "/images/chillupwebdashboard/Create_%20New%20Class%202.png",
        "/images/chillupwebdashboard/Dashboard%203%20-%20Notifications.png",
        "/images/chillupwebdashboard/vendor%20thank%20you.png",
        "/images/chillupwebdashboard/Create_%20New%20Class%201.png",
        "/images/chillupwebdashboard/vendor%20sign%20in.png",
        "/images/chillupwebdashboard/Create_%20New%20Class%206.png",
        "/images/chillupwebdashboard/Create_%20New%20Class%207.png",
        "/images/chillupwebdashboard/Dashboard%202.png"
    ],

    ChillupBackend: [
        "/images/chilllupbackend/Ads%202.png",
        "/images/chilllupbackend/Notifications%201.png",
        "/images/chilllupbackend/Ads%201.png",
        "/images/chilllupbackend/Vendor%20Ads%202.png",
        "/images/chilllupbackend/Vendor%20Ads%201.png",
        "/images/chilllupbackend/AddSchoolRequest.png",
        "/images/chilllupbackend/Feedback%202.png",
        "/images/chilllupbackend/Feedback%201.png",
        "/images/chilllupbackend/Vendors%201.png",
        "/images/chilllupbackend/Trends%201.png",
        "/images/chilllupbackend/Vendors%202.png",
        "/images/chilllupbackend/Trends%202.png",
        "/images/chilllupbackend/Trends%203.png",
        "/images/chilllupbackend/Vendors%203.png",
        "/images/chilllupbackend/Vendors%204.png",
        "/images/chilllupbackend/Vendors%205.png",
        "/images/chilllupbackend/Vendor%20Reviews%202.png",
        "/images/chilllupbackend/Vendor%20Reviews%201.png",
    ],


    Calender: [
        "/images/calender/Event.png",
        "/images/calender/Event%202.png",
        "/images/calender/Homepage.png"
    ],

    springringTeacherPortal: [
        "/images/springringteacherportal/Class%20Details.jpg",
        "/images/springringteacherportal/Class%20Registry%20-%20Students.jpg",
        "/images/springringteacherportal/Posts_%20Event%20-%20Post%20to%20Users%20-%20Popup.png",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Media%20Post%20-%20Step%202%20Attachment%20&%20Alert%20-%20Post%20to%20Users.png",
        "/images/springringteacherportal/Posts_%20Appointment%20(In-Person)%20View%20Results.png",
        "/images/springringteacherportal/Posts_%20Images.png",
        "/images/springringteacherportal/Chat_Personal%20Chat%20Disabled.jpg",
        "/images/springringteacherportal/Posts_%20Event.png",
        "/images/springringteacherportal/Whole%20School%20Details.jpg",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Authorization%20-%20Step%202%20Event.png",
        "/images/springringteacherportal/Posts_%20Link.png",
        "/images/springringteacherportal/Posts_%20Authorization%20View%20Results.png",
        "/images/springringteacherportal/Student%20Diary_Diary%20Board.jpg",
        "/images/springringteacherportal/Archived%20Boards%20-%20Classes.jpg",
        "/images/springringteacherportal/Edit%20Class.jpg",
        "/images/springringteacherportal/Class%20Registry%20-%20Students%20Profile.jpg",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Appointment%20(Video)%20-%20Step%202.png",
        "/images/springringteacherportal/Profile%20&%20Settings.jpg",
        "/images/springringteacherportal/Create%20Class%20-%20Add%20Individual%20users.png",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Media%20Post%20-%20Step%201%20Boards.png",
        "/images/springringteacherportal/Chat%204.jpg",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Media%20Post%20-%20Step%201%20Users.png",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Event%20-%20Step%201%20Users.png",
        "/images/springringteacherportal/Chat%202.png",
        "/images/springringteacherportal/Posts_%20Event%20-%20Post%20to%20Users.png",
        "/images/springringteacherportal/Archived%20board.jpg",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Media%20Post%20-%20Step%202%20Images%20&%20Alert.png",
        "/images/springringteacherportal/Chat%201.jpg",
        "/images/springringteacherportal/Posts_%20Appointment%20(Video)%20View%20Results.png",
        "/images/springringteacherportal/All%20Updates_New%20comments.png",
        "/images/springringteacherportal/Calendar%20-%20Agenda.png",
        "/images/springringteacherportal/Student%20Diary_Diary%20Board%20-%20Viewer.jpg",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Link%20Post%20-%20Step%201%20Boards.png",
        "/images/springringteacherportal/TW%20Chat%204.jpg",
        "/images/springringteacherportal/Create%20New%20Post%20-%20Media%20Post%20-%20Step%202%20Attachment%20&%20Alert.png",
        "/images/springringteacherportal/Profile%20&%20Settings%20-%20Chat%20and%20Office%20Hours%20-%20Enabled.png",
        "/images/springringteacherportal/Student%20Diary_View%20Post_Attachment.jpg",
        "/images/springringteacherportal/Class%20Registry%20-%20Students-1.jpg",
    ],

    Bahrain: [
        "/images/bahrain/Homepage%202.png",
        "/images/Bahrain/DESKTOP Bahrain's Map.png",
        "/images/bahrain/Desktop%20Homepage.png",
        "/images/bahrain/DESKTOP%20My%20Itinerary.png",
        "/images/bahrain/DESKTOP%20Journey%20(Culture)%201.png",
        "/images/bahrain/DESKTOP%20Where%20to%20stay.png",
        "/images/bahrain/DESKTOP%20Places%20to%20Eat%203.png",
        "/images/bahrain/DESKTOP%20Journey%20(Taste).png",
        "/images/bahrain/Things%20to%20do.png",
        "/images/bahrain/DESKTOP%20Media%20-%20Images.png",
        "/images/bahrain/DESKTOP%20Media%20-%20Press%20Releases.png",
        "/images/bahrain/Explore%20more%20article%202.png",
        "/images/bahrain/DESKTOP%20Where%20to%20stay%20Inside.png"
    ],

    SpringringAdminWeb: [
        "/images/springringadminweb/User%20Profile/Edit%20-%20Student%20&%20One%20Parent%20-%20Groups%20Dropdown.png",
        "/images/springringadminweb/User%20Profile/Edit%20-%20Admin.png",
        "/images/springringadminweb/Dashboard.png",
        "/images/springringadminweb/School%20Calendar%20-%20Month.png",
        "/images/springringadminweb/Manage%20Users%20-%20Add%20user%20Admin.png",
        "/images/springringadminweb/Manage%20Boards%20-%20Archives.png",
        "/images/springringadminweb/School%20Calendar%20-%20Agenda.png",
        "/images/springringadminweb/School%20Profile%20&%20Settings%20-%20School%20Profile.png",
        "/images/springringadminweb/User%20Profile%20-%20Student%20&%20Parents.png",
        "/images/springringadminweb/Import%202.png",
        "/images/springringadminweb/Create%20Board%20-%20Add%20Individual%20users.png",
        "/images/springringadminweb/Import%209%20-%20Tags.png",
        "/images/springringadminweb/School%20Profile%20&%20Settings%20-%20Chat.png",
        "/images/springringadminweb/Manage%20Users%20-%20Add%20user%20Leader.png",
        "/images/springringadminweb/Create%20Group%20-%20Add%20Individual%20users%20-%20Loading.png",
        "/images/springringadminweb/Manage%20Boards%20-%20School%20Boards.png",
        "/images/springringadminweb/Manage%20Users%20-%20Add%20user.png",
        "/images/springringadminweb/Roll-over%2011.png",
        "/images/springringadminweb/Roll-over%2012.png",
        "/images/springringadminweb/Create%20Group.png",
        "/images/springringadminweb/Create%20Group%20-%20Add%20Individual%20users.png",
        "/images/springringadminweb/Saving%20behaviour%205.png",
        "/images/springringadminweb/School%20Contacts%20Edit.png",
        "/images/springringadminweb/Billing%20-%20Choose%20Plan.png",
        "/images/springringadminweb/Manage%20Groups.png",
        "/images/springringadminweb/Dashboard%202.png",
    ],

    Directory: [
        "/images/directory/Site%20Contacts%20-%20View%20Group.png",
        "/images/directory/Login.png",
        "/images/directory/Groups%20Details%20-%20User%20Profile.png",
        "/images/directory/Staff%20-%20User%20Selection.png",
        "/images/directory/Groups%20Details%20-%20Group%20from%20user.png",
        "/images/directory/Site%20Contacts.png",
        "/images/directory/Groups.png",
        "/images/directory/Groups%20Details.png",
        "/images/directory/Staff.png",
        "/images/directory/Site%20Contacts%20-%20Staff%20Profile.png",
        "/images/directory/Staff%20-%20Staff%20Profile.png",
    ],

    ECA: [
        "/images/eca/Cart.png",
        "/images/eca/Homepage%20login.png",
        "/images/eca/Confirmation.png",
        "/images/eca/Checkout%20Paid.png",
        "/images/eca/Checkout%20Free_%20pop%20up.png",
        "/images/eca/Checkout%20Free.png",
        "/images/eca/Profile.png"
    ],

    AwalTerminal: [
        "/images/awalterminal/Option%201%20-%20Tour@1x.png",
        "/images/awalterminal/General%20Aviation%20Form_1@1x.svg",
        "/images/awalterminal/Elite%20Form_2@1x.svg",
        "/images/awalterminal/Option%201%20-%20Home@2x.png",
        "/images/awalterminal/Elite%20Form_4@1x.svg",
        "/images/awalterminal/Option%201%20-%20Services_General%20Aviation@1x.png",
        "/images/awalterminal/Option%201%20-%20Contact%20Us@1x.png",
        "/images/awalterminal/Option%201%20-%20Our%20Story@1x.png",
        "/images/awalterminal/Elite%20Form_6@1x.svg",
        "/images/awalterminal/Payment%202@1x.svg",
        "/images/awalterminal/General%20Aviation%20Form_5@1x.svg",
        "/images/awalterminal/Elite%20Form_3@1x.svg",
        "/images/awalterminal/Elite%20Form_1@1x.svg",
        "/images/awalterminal/General%20Aviation%20Form_6@1x.svg",
        "/images/awalterminal/Payment%201@1x.svg",
        "/images/awalterminal/Elite%20Form_5@1x.svg",
        "/images/awalterminal/Elite%20Form_7@1x.svg",
    ],

    safercare: [
        "/images/safercare/image_original-1.jpg",
        "/images/safercare/image_original.jpg",
        "/images/safercare/image_original_2.jpg",
        "/images/safercare/image_original_4.jpg",
        "/images/safercare/image_original_6.jpg"
    ],

    ChillupMobile: [
        "/images/chillupmobile/Home%20-%20School.png",
        "/images/chillupmobile/Home%20-%20Review%20Notice.png",
        "/images/chillupmobile/Kid2%20Home%20-%20No%20Activity.png",
        "/images/chillupmobile/Filters.png",
        "/images/chillupmobile/Notifications-1.png",
        "/images/chillupmobile/Review%20Order.png",
        "/images/chillupmobile/Onboarding%204.png",
        "/images/chillupmobile/Vendor%20Page%20-%20Info.png",
        "/images/chillupmobile/Verify%20Mobile%20Number.png",
        "/images/chillupmobile/School%20Info%203.png",
        "/images/chillupmobile/Booked.png",
        "/images/chillupmobile/School%20Info%201.png",
        "/images/chillupmobile/Home%20-%20Activity.png",
        "/images/chillupmobile/Vendors%20List.png",
        "/images/chillupmobile/Kid2%20Home%20-%20Settings%20Interests.png",
        "/images/chillupmobile/Kid2%20Home%20-%20Settings%20Colors.png",
        "/images/chillupmobile/Create%20Event.png",
        "/images/chillupmobile/Vendor%20Page%20-%20Profile.png",
        "/images/chillupmobile/Splash.png",
        "/images/chillupmobile/Create%20Activity%20Select%20End%20Date.png",
        "/images/chillupmobile/Class%20details%20(Free).png",
        "/images/chillupmobile/Notifications.png",
        "/images/chillupmobile/Shopping%20Bag.png",
        "/images/chillupmobile/Hearts.png",
        "/images/chillupmobile/Profile.png",
        "/images/chillupmobile/Create%20Activity%20Select%20From%20Date.png",
        "/images/chillupmobile/Filters%20-%20One%20Option.png",
        "/images/chillupmobile/Calendar%20-%20Agenda.png",
        "/images/chillupmobile/Categories.png",
        "/images/chillupmobile/Calendar%20-%20Month.png",
        "/images/chillupmobile/Home%20-%20Settings.png",
        "/images/chillupmobile/Complate%20your%20profile.png",
        "/images/chillupmobile/Create%20Activity.png",
    ],

    chillupPublicWebsite: [
        "/images/chilluppublicwebsite/Vendor.png",
        "/images/chilluppublicwebsite/Parent.png",
        "/images/chilluppublicwebsite/FAQ.png",
        "/images/chilluppublicwebsite/Contact%20Us.png",
        "/images/chilluppublicwebsite/About.png",
        "/images/chilluppublicwebsite/Legal%20Info.png",
    ],

    naturallockbox: [
        "/images/naturallockbox/image_original-6.jpg",
        "/images/naturallockbox/.DS_Store",
        "/images/naturallockbox/image_original.JPG",
        "/images/naturallockbox/image_original_5.jpg",
        "/images/naturallockbox/image_original_4.JPG",
        "/images/naturallockbox/image_original_7.jpg",
        "/images/naturallockbox/image_original_3.JPG",
        "/images/naturallockbox/image_original_1.JPG",
    ],

    Admissions: [
        "/images/admissions/EoI_Expired.png",
        "/images/admissions/EoI%20Details.png",
        "/images/admissions/Application%201.png",
        "/images/admissions/Application%203.png",
        "/images/admissions/Offer%201.png",
        "/images/admissions/EoI%20Form%204.png",
        "/images/admissions/EoI%20Form%205.png",
        "/images/admissions/EoI%20Form%206.png"
    ],

    FRC: [
        "/images/pdpfrc/Login.png",
        "/images/pdpfrc/Parent%20View.png",
        "/images/pdpfrc/Analytics.png",
        "/images/pdpfrc/Create%20Unit%20-%20Topic.png",
        "/images/pdpfrc/Parent%20View%20-%20Subject%20Music.png",
        "/images/pdpfrc/Parent%20View%20-%20Assessment%20Modes.png"
    ],

    PDP: [
        "/images/pdp/Teacher%20Leader_Pedagogical%20focus.png",
        "/images/pdp/Teacher%20Leader_Strategic%20Priorities%20-%20Future%20Ready%20Curriculum.png",
        "/images/pdp/Teacher%20Leader_Leadership%20Focus.png",
        "/images/pdp/Teacher%20Leader_Home.png",
        "/images/pdp/Teacher%20Leader_Self%20Evaluation.png",
    ],

    SPEA: [
        "/images/spea/Investors%20-%20School%20View%204.png",
        "/images/spea/Parent%2008.png",
        "/images/spea/Investors%20-%20School%20View%201.png",
        "/images/spea/Parent%2003.png",
        "/images/spea/Forecast.png",
        "/images/spea/Parent%2002.png",
        "/images/spea/Parent%2001.png",
        "/images/spea/Parent%2006.png",
    ],

};

export default ProjectGalleries;
