// /data/ProjectGalleries.js

const ProjectGalleries = {
    Lokal: [
        "/images/lokal/admin---designers-4-(view-products).png",
        "/images/lokal/login.png",
        "/images/lokal/designer---add-product-(clothing).png",
        "/images/lokal/super-admin---orders-5.png",
        "/images/lokal/super-admin---orders-4.png",
        "/images/lokal/admin---designers-2-(add).png",
        "/images/lokal/super-admin---orders-1.png",
        "/images/lokal/become-a-lokal-vendor-1.png",
        "/images/lokal/super-admin---orders-3.png",
        "/images/lokal/super-admin---orders-2.png",
        "/images/lokal/admin---finance-2.png",
        "/images/lokal/super-admin---create-order-1.png",
        "/images/lokal/designer---add-product-(home-&-gifts).png",
        "/images/lokal/designer---business-settings-1.png",
        "/images/lokal/admin---designers-1.png",
        "/images/lokal/admin---pending-approval.png",
        "/images/lokal/designer---products.png"
    ],

    MyStartCloud: [
        "/images/mystartcloud/icons-library.png",
        "/images/mystartcloud/new-collection---custom-apps-2.png",
        "/images/mystartcloud/social-media-feed.png",
        "/images/mystartcloud/sp---forgot-password.png",
        "/images/mystartcloud/users.png",
        "/images/mystartcloud/school-settings.png",
        "/images/mystartcloud/collections---edit-app.png",
        "/images/mystartcloud/new-collection---details.png",
        "/images/mystartcloud/sp---private---login.png",
        "/images/mystartcloud/new-collection---cloud-apps-1.png",
        "/images/mystartcloud/announcement.png",
        "/images/mystartcloud/new-collection---cloud-apps-2.png",
        "/images/mystartcloud/collections---edit-group.png",
        "/images/mystartcloud/collections.png",
        "/images/mystartcloud/1440px---home.png",
        "/images/mystartcloud/registerations-1.png",
        "/images/mystartcloud/1440px---note-fullscreen.png",
        "/images/mystartcloud/billing.png",
    ],

    NaseebiMobile: [
        "/images/naseebimobile/create-2b.png",
        "/images/naseebimobile/sign-in.png",
        "/images/naseebimobile/your-avatar.png",
        "/images/naseebimobile/settings.png",
        "/images/naseebimobile/pricing.png",
        "/images/naseebimobile/match-profile---free.png",
        "/images/naseebimobile/match-profile_not-for-me-2.png",
        "/images/naseebimobile/create-6.png",
        "/images/naseebimobile/create-7.png",
        "/images/naseebimobile/create-1.png",
        "/images/naseebimobile/complete-profile.png",
        "/images/naseebimobile/tour-2.png",
        "/images/naseebimobile/chat-4.png",
        "/images/naseebimobile/your-connections-1.png",
        "/images/naseebimobile/tour-3.png",
        "/images/naseebimobile/your-connections-3.png",
        "/images/naseebimobile/match-profile---paid,-connected.png",
        "/images/naseebimobile/coming-soon.png",
        "/images/naseebimobile/chat-2.png",
        "/images/naseebimobile/chat-1.png",
        "/images/naseebimobile/match-profile---connect-popup.png",
        "/images/naseebimobile/your-profile-2.png",
        "/images/naseebimobile/my-profile-1.png",
        "/images/naseebimobile/home_loading_male.png",
        "/images/naseebimobile/your-profile-1.png",
        "/images/naseebimobile/preferences-6.png",
        "/images/naseebimobile/home-1.png",
        "/images/naseebimobile/need-more-time.png",
        "/images/naseebimobile/your-profile_add-photos.png"
    ],

    Cazasouq: [
        "/images/cazasouq/wishlist.png",
        "/images/cazasouq/checkout---address.png",
        "/images/cazasouq/products-list---product-details-2.png",
        "/images/cazasouq/search---clicked.png",
        "/images/cazasouq/checkout---finished.png",
        "/images/cazasouq/onboarding-1.png",
        "/images/cazasouq/products-list---product-details-1.png",
        "/images/cazasouq/currencies.png",
        "/images/cazasouq/settings.png",
        "/images/cazasouq/settings-after-login.png",
        "/images/cazasouq/checkout---payment.png",
        "/images/cazasouq/login-or-create-account.png",
        "/images/cazasouq/checkout---preview.png",
        "/images/cazasouq/view-your-order-history.png",
        "/images/cazasouq/checkout---shipping.png",
        "/images/cazasouq/splash.png",
        "/images/cazasouq/menu.png",
        "/images/cazasouq/menu-open.png",
        "/images/cazasouq/currency.png",
        "/images/cazasouq/products-list.png",
        "/images/cazasouq/categories.png",
        "/images/cazasouq/order-details-4.png",
        "/images/cazasouq/search-results.png",
        "/images/cazasouq/reset-password-2.png",
        "/images/cazasouq/order-details-1.png",
        "/images/cazasouq/order-details-2.png"
    ],

    Chillupwebdashboard: [
        "/images/chillupwebdashboard/products-1.png",
        "/images/chillupwebdashboard/transactions.png",
        "/images/chillupwebdashboard/follows-&-reviews.png",
        "/images/chillupwebdashboard/vendor-register-2.png",
        "/images/chillupwebdashboard/create_-new-class-5-(fixed-terms).png",
        "/images/chillupwebdashboard/account-3_my-profile.png",
        "/images/chillupwebdashboard/products-2---view-product-(slots).png",
        "/images/chillupwebdashboard/vendor-register-1.png",
        "/images/chillupwebdashboard/account-4.png",
        "/images/chillupwebdashboard/create_-new-class-4-(fixed-terms).png",
        "/images/chillupwebdashboard/customer-list-1.png",
        "/images/chillupwebdashboard/account-6_plan-super-chill.png",
        "/images/chillupwebdashboard/customer-list-2.png",
        "/images/chillupwebdashboard/account2.png",
        "/images/chillupwebdashboard/create_-new-class-5-(period).png",
        "/images/chillupwebdashboard/bookings-1.png",
        "/images/chillupwebdashboard/customer-list_free-plan.png",
        "/images/chillupwebdashboard/create_-new-class-4-(period).png",
        "/images/chillupwebdashboard/create_-new-class-2.png",
        "/images/chillupwebdashboard/dashboard-3---notifications.png",
        "/images/chillupwebdashboard/vendor-thank-you.png",
        "/images/chillupwebdashboard/create_-new-class-1.png",
        "/images/chillupwebdashboard/vendor-sign-in.png",
        "/images/chillupwebdashboard/create_-new-class-6.png",
        "/images/chillupwebdashboard/create_-new-class-7.png",
        "/images/chillupwebdashboard/dashboard-2.png"
    ],

    ChillupBackend: [
        "/images/chilllupbackend/ads-2.png",
        "/images/chilllupbackend/notifications-1.png",
        "/images/chilllupbackend/ads-1.png",
        "/images/chilllupbackend/vendor-ads-2.png",
        "/images/chilllupbackend/vendor-ads-1.png",
        "/images/chilllupbackend/addschoolrequest.png",
        "/images/chilllupbackend/feedback-2.png",
        "/images/chilllupbackend/feedback-1.png",
        "/images/chilllupbackend/vendors-1.png",
        "/images/chilllupbackend/trends-1.png",
        "/images/chilllupbackend/vendors-2.png",
        "/images/chilllupbackend/trends-2.png",
        "/images/chilllupbackend/trends-3.png",
        "/images/chilllupbackend/vendors-3.png",
        "/images/chilllupbackend/vendors-4.png",
        "/images/chilllupbackend/vendors-5.png",
        "/images/chilllupbackend/vendor-reviews-2.png",
        "/images/chilllupbackend/vendor-reviews-1.png",
    ],


    Calender: [
        "/images/calenderproject/event.png",
        "/images/calenderproject/event-2.png",
        "/images/calenderproject/homepage.png"
    ],

    springringTeacherPortal: [
        "/images/springringteacherportalproject/class-details.jpg",
        "/images/springringteacherportalproject/class-registry---students.jpg",
        "/images/springringteacherportalproject/posts_-event---post-to-users---popup.png",
        "/images/springringteacherportalproject/create-new-post---media-post---step-2-attachment-&-alert---post-to-users.png",
        "/images/springringteacherportalproject/posts_-appointment-(in-person)-view-results.png",
        "/images/springringteacherportalproject/posts_-images.png",
        "/images/springringteacherportalproject/chat_personal-chat-disabled.jpg",
        "/images/springringteacherportalproject/posts_-event.png",
        "/images/springringteacherportalproject/whole-school-details.jpg",
        "/images/springringteacherportalproject/create-new-post---authorization---step-2-event.png",
        "/images/springringteacherportalproject/posts_-link.png",
        "/images/springringteacherportalproject/posts_-authorization-view-results.png",
        "/images/springringteacherportalproject/student-diary_diary-board.jpg",
        "/images/springringteacherportalproject/archived-boards---classes.jpg",
        "/images/springringteacherportalproject/edit-class.jpg",
        "/images/springringteacherportalproject/class-registry---students-profile.jpg",
        "/images/springringteacherportalproject/create-new-post---appointment-(video)---step-2.png",
        "/images/springringteacherportalproject/profile-&-settings.jpg",
        "/images/springringteacherportalproject/create-class---add-individual-users.png",
        "/images/springringteacherportalproject/create-new-post---media-post---step-1-boards.png",
        "/images/springringteacherportalproject/chat-4.jpg",
        "/images/springringteacherportalproject/create-new-post---media-post---step-1-users.png",
        "/images/springringteacherportalproject/create-new-post---event---step-1-users.png",
        "/images/springringteacherportalproject/chat-2.png",
        "/images/springringteacherportalproject/posts_-event---post-to-users.png",
        "/images/springringteacherportalproject/archived-board.jpg",
        "/images/springringteacherportalproject/create-new-post---media-post---step-2-images-&-alert.png",
        "/images/springringteacherportalproject/chat-1.jpg",
        "/images/springringteacherportalproject/posts_-appointment-(video)-view-results.png",
        "/images/springringteacherportalproject/all-updates_new-comments.png",
        "/images/springringteacherportalproject/calendar---agenda.png",
        "/images/springringteacherportalproject/student-diary_diary-board---viewer.jpg",
        "/images/springringteacherportalproject/create-new-post---link-post---step-1-boards.png",
        "/images/springringteacherportalproject/tw-chat-4.jpg",
        "/images/springringteacherportalproject/create-new-post---media-post---step-2-attachment-&-alert.png",
        "/images/springringteacherportalproject/profile-&-settings---chat-and-office-hours---enabled.png",
        "/images/springringteacherportalproject/student-diary_view-post_attachment.jpg",
        "/images/springringteacherportalproject/class-registry---students-1.jpg",
    ],

    Bahrain: [
        "/images/bahrain/homepage-2.png",
        "/images/Bahrain/DESKTOP Bahrain's Map.png",
        "/images/bahrain/desktop-homepage.png",
        "/images/bahrain/desktop-my-itinerary.png",
        "/images/bahrain/desktop-journey-(culture)-1.png",
        "/images/bahrain/desktop-where-to-stay.png",
        "/images/bahrain/desktop-places-to-eat-3.png",
        "/images/bahrain/desktop-journey-(taste).png",
        "/images/bahrain/things-to-do.png",
        "/images/bahrain/desktop-media---images.png",
        "/images/bahrain/desktop-media---press-releases.png",
        "/images/bahrain/explore-more-article-2.png",
        "/images/bahrain/desktop-where-to-stay-inside.png"
    ],

    SpringringAdminWeb: [
        "/images/springringadminwebproject/edit---student-&-one-parent---groups-dropdown.png",
        "/images/springringadminwebproject/edit---admin.png",
        "/images/springringadminwebproject/dashboard.jpg",
        "/images/springringadminwebproject/school-calendar---month.png",
        "/images/springringadminwebproject/manage-users---add-user-admin.png",
        "/images/springringadminwebproject/manage-boards---archives.png",
        "/images/springringadminwebproject/school-calendar---agenda.png",
        "/images/springringadminwebproject/school-profile-&-settings---school-profile.png",
        "/images/springringadminwebproject/user-profile---student-&-parents.png",
        "/images/springringadminwebproject/import-2.png",
        "/images/springringadminwebproject/create-board---add-individual-users.png",
        "/images/springringadminwebproject/import-9---tags.png",
        "/images/springringadminwebproject/school-profile-&-settings---chat.png",
        "/images/springringadminwebproject/manage-users---add-user-leader.png",
        "/images/springringadminwebproject/create-group---add-individual-users---loading.png",
        "/images/springringadminwebproject/manage-boards---school-boards.png",
        "/images/springringadminwebproject/manage-users---add-user.png",
        "/images/springringadminwebproject/roll-over-11.png",
        "/images/springringadminwebproject/roll-over-12.png",
        "/images/springringadminwebproject/create-group.png",
        "/images/springringadminwebproject/create-group---add-individual-users.png",
        "/images/springringadminwebproject/saving-behaviour-5.png",
        "/images/springringadminwebproject/school-contacts-edit.png",
        "/images/springringadminwebproject/billing---choose-plan.png",
        "/images/springringadminwebproject/manage-groups.png",
        "/images/springringadminwebproject/dashboard-2.png",
    ],

    Directory: [
        "/images/directory/site-contacts---view-group.png",
        "/images/directory/login.png",
        "/images/directory/groups-details---user-profile.png",
        "/images/directory/staff---user-selection.png",
        "/images/directory/groups-details---group-from-user.png",
        "/images/directory/site-contacts.png",
        "/images/directory/groups.png",
        "/images/directory/groups-details.png",
        "/images/directory/staff.png",
        "/images/directory/site-contacts---staff-profile.png",
        "/images/directory/staff---staff-profile.png",
    ],

    ECA: [
        "/images/eca/cart.png",
        "/images/eca/homepage-login.png",
        "/images/eca/confirmation.png",
        "/images/eca/checkout-paid.png",
        "/images/eca/checkout-free_-pop-up.png",
        "/images/eca/checkout-free.png",
        "/images/eca/profile.png"
    ],

    AwalTerminal: [
        "/images/awalterminal/option-1---tour@1x.png",
        "/images/awalterminal/general-aviation-form_1@1x.svg",
        "/images/awalterminal/elite-form_2@1x.svg",
        "/images/awalterminal/option-1---home@2x.png",
        "/images/awalterminal/elite-form_4@1x.svg",
        "/images/awalterminal/option-1---services_general-aviation@1x.png",
        "/images/awalterminal/option-1---contact-us@1x.png",
        "/images/awalterminal/option-1---our-story@1x.png",
        "/images/awalterminal/elite-form_6@1x.svg",
        "/images/awalterminal/payment-2@1x.svg",
        "/images/awalterminal/general-aviation-form_5@1x.svg",
        "/images/awalterminal/elite-form_3@1x.svg",
        "/images/awalterminal/elite-form_1@1x.svg",
        "/images/awalterminal/general-aviation-form_6@1x.svg",
        "/images/awalterminal/payment-1@1x.svg",
        "/images/awalterminal/elite-form_5@1x.svg",
        "/images/awalterminal/elite-form_7@1x.svg",
    ],

    safercare: [
        "/images/safercare/image_original-1.jpg",
        "/images/safercare/image_original.jpg",
        "/images/safercare/image_original_2.jpg",
        "/images/safercare/image_original_4.jpg",
        "/images/safercare/image_original_6.jpg"
    ],

    ChillupMobile: [
        "/images/chillupmobile/home---school.png",
        "/images/chillupmobile/home---review-notice.png",
        "/images/chillupmobile/kid2-home---no-activity.png",
        "/images/chillupmobile/filters.png",
        "/images/chillupmobile/notifications-1.png",
        "/images/chillupmobile/review-order.png",
        "/images/chillupmobile/onboarding-4.png",
        "/images/chillupmobile/vendor-page---info.png",
        "/images/chillupmobile/verify-mobile-number.png",
        "/images/chillupmobile/school-info-3.png",
        "/images/chillupmobile/booked.png",
        "/images/chillupmobile/school-info-1.png",
        "/images/chillupmobile/home---activity.png",
        "/images/chillupmobile/vendors-list.png",
        "/images/chillupmobile/kid2-home---settings-interests.png",
        "/images/chillupmobile/kid2-home---settings-colors.png",
        "/images/chillupmobile/create-event.png",
        "/images/chillupmobile/vendor-page---profile.png",
        "/images/chillupmobile/splash.png",
        "/images/chillupmobile/create-activity-select-end-date.png",
        "/images/chillupmobile/class-details-(free).png",
        "/images/chillupmobile/notifications.png",
        "/images/chillupmobile/shopping-bag.png",
        "/images/chillupmobile/hearts.png",
        "/images/chillupmobile/profile.png",
        "/images/chillupmobile/create-activity-select-from-date.png",
        "/images/chillupmobile/filters---one-option.png",
        "/images/chillupmobile/calendar---agenda.png",
        "/images/chillupmobile/categories.png",
        "/images/chillupmobile/calendar---month.png",
        "/images/chillupmobile/home---settings.png",
        "/images/chillupmobile/complate-your-profile.png",
        "/images/chillupmobile/create-activity.png",
    ],

    chillupPublicWebsite: [
        "/images/chilluppublicwebsiteProject/vendor.png",
        "/images/chilluppublicwebsiteProject/parent.png",
        "/images/chilluppublicwebsiteProject/faq.png",
        "/images/chilluppublicwebsiteProject/contact-us.png",
        "/images/chilluppublicwebsiteProject/about.png",
        "/images/chilluppublicwebsiteProject/legal-info.png",
    ],

    naturallockbox: [
        "/images/naturallockboxproject/image_original-6.jpg",
        "/images/naturallockboxproject/.DS_Store",
        "/images/naturallockboxproject/image_original.jpg",
        "/images/naturallockboxproject/image_original_5.jpg",
        "/images/naturallockboxproject/image_original_4.jpg",
        "/images/naturallockboxproject/image_original_7.jpg",
        "/images/naturallockboxproject/image_original_3.jpg",
        "/images/naturallockboxproject/image_original_1.jpg",
    ],

    Admissions: [
        "/images/admissions/eoi_expired.png",
        "/images/admissions/eoi-details.png",
        "/images/admissions/application-1.png",
        "/images/admissions/application-3.png",
        "/images/admissions/offer-1.png",
        "/images/admissions/eoi-form-4.png",
        "/images/admissions/eoi-form-5.png",
        "/images/admissions/eoi-form-6.png"
    ],

    FRC: [
        "/images/pdpfrcproject/login.png",
        "/images/pdpfrcproject/parent-view.png",
        "/images/pdpfrcproject/analytics.png",
        "/images/pdpfrcproject/create-unit---topic.png",
        "/images/pdpfrcproject/parent-view---subject-music.png",
        "/images/pdpfrcproject/parent-view---assessment-modes.png"
    ],

    PDP: [
        "/images/pdp/teacher-leader_pedagogical-focus.png",
        "/images/pdp/teacher-leader_strategic-priorities---future-ready-curriculum.png",
        "/images/pdp/teacher-leader_leadership-focus.png",
        "/images/pdp/teacher-leader_home.png",
        "/images/pdp/teacher-leader_self-evaluation.png",
    ],

    SPEA: [
        "/images/spea/investors---school-view-4.png",
        "/images/spea/parent-08.png",
        "/images/spea/investors---school-view-1.png",
        "/images/spea/parent-03.png",
        "/images/spea/forecast.png",
        "/images/spea/parent-02.png",
        "/images/spea/parent-01.png",
        "/images/spea/parent-06.png",
    ],

};

export default ProjectGalleries;
