// /data/ProjectGalleries.js

const ProjectGalleries = {
    Lokal: [
        "/images/Lokal/Admin - Designers 4 (view products).png",
        "/images/Lokal/Login.png",
        "/images/Lokal/Designer - Add Product (Clothing).png",
        "/images/Lokal/Super Admin - Orders 5.png",
        "/images/Lokal/Super Admin - Orders 4.png",
        "/images/Lokal/Admin - Designers 2 (add).png",
        "/images/Lokal/Super Admin - Orders 1.png",
        "/images/Lokal/Become a Lokal Vendor 1.png",
        "/images/Lokal/Super Admin - Orders 3.png",
        "/images/Lokal/Super Admin - Orders 2.png",
        "/images/Lokal/Admin - Finance 2.png",
        "/images/Lokal/Super Admin - Create Order 1.png",
        "/images/Lokal/Designer - Add Product (Home & Gifts).png",
        "/images/Lokal/Designer - Business Settings 1.png",
        "/images/Lokal/Admin - Designers 1.png",
        "/images/Lokal/Admin - Pending Approval.png",
        "/images/Lokal/Designer - Products.png"
    ],

    MyStartCloud: [
        "/images/Mystartcloud/Icons Library.png",
        "/images/Mystartcloud/New Collection - Custom Apps 2.png",
        "/images/Mystartcloud/Social media feed.png",
        "/images/Mystartcloud/SP - Forgot Password.png",
        "/images/Mystartcloud/Users.png",
        "/images/Mystartcloud/School Settings.png",
        "/images/Mystartcloud/Collections - Edit App.png",
        "/images/Mystartcloud/New Collection - Details.png",
        "/images/Mystartcloud/SP - Private - Login.png",
        "/images/Mystartcloud/New Collection - Cloud Apps 1.png",
        "/images/Mystartcloud/Announcement.png",
        "/images/Mystartcloud/New Collection - Cloud Apps 2.png",
        "/images/Mystartcloud/Collections - Edit Group.png",
        "/images/Mystartcloud/Collections.png",
        "/images/Mystartcloud/1440px - Home.png",
        "/images/Mystartcloud/Registerations 1.png",
        "/images/Mystartcloud/1440px - Note Fullscreen.png",
        "/images/Mystartcloud/Billing.png",
    ],

    NaseebiMobile: [
        "/images/NaseebiMobile/Create 2b.png",
        "/images/NaseebiMobile/Sign in.png",
        "/images/NaseebiMobile/Your Avatar.png",
        "/images/NaseebiMobile/Settings.png",
        "/images/NaseebiMobile/Pricing.png",
        "/images/NaseebiMobile/Match Profile - Free.png",
        "/images/NaseebiMobile/Match Profile_Not for me 2.png",
        "/images/NaseebiMobile/Create 6.png",
        "/images/NaseebiMobile/Create 7.png",
        "/images/NaseebiMobile/Create 1.png",
        "/images/NaseebiMobile/Complete profile.png",
        "/images/NaseebiMobile/Tour 2.png",
        "/images/NaseebiMobile/Chat 4.png",
        "/images/NaseebiMobile/Your Connections 1.png",
        "/images/NaseebiMobile/Tour 3.png",
        "/images/NaseebiMobile/Your Connections 3.png",
        "/images/NaseebiMobile/Match Profile - Paid, Connected.png",
        "/images/NaseebiMobile/Coming Soon.png",
        "/images/NaseebiMobile/Chat 2.png",
        "/images/NaseebiMobile/Chat 1.png",
        "/images/NaseebiMobile/Match Profile - Connect Popup.png",
        "/images/NaseebiMobile/Your profile 2.png",
        "/images/NaseebiMobile/My Profile 1.png",
        "/images/NaseebiMobile/Home_Loading_Male.png",
        "/images/NaseebiMobile/Your profile 1.png",
        "/images/NaseebiMobile/Preferences 6.png",
        "/images/NaseebiMobile/Home 1.png",
        "/images/NaseebiMobile/Need more time.png",
        "/images/NaseebiMobile/Your Profile_Add photos.png"
    ],

    Cazasouq: [
        "/images/Cazasouq/Wishlist.png",
        "/images/Cazasouq/Checkout - Address.png",
        "/images/Cazasouq/Products List - Product Details 2.png",
        "/images/Cazasouq/Search - Clicked.png",
        "/images/Cazasouq/Checkout - Finished.png",
        "/images/Cazasouq/Onboarding 1.png",
        "/images/Cazasouq/Products List - Product Details 1.png",
        "/images/Cazasouq/Currencies.png",
        "/images/Cazasouq/Settings.png",
        "/images/Cazasouq/Settings After Login.png",
        "/images/Cazasouq/Checkout - Payment.png",
        "/images/Cazasouq/Login or Create Account.png",
        "/images/Cazasouq/Checkout - Preview.png",
        "/images/Cazasouq/View your order history.png",
        "/images/Cazasouq/Checkout - Shipping.png",
        "/images/Cazasouq/Splash.png",
        "/images/Cazasouq/Menu.png",
        "/images/Cazasouq/Menu Open.png",
        "/images/Cazasouq/Currency.png",
        "/images/Cazasouq/Products List.png",
        "/images/Cazasouq/Categories.png",
        "/images/Cazasouq/Order Details 4.png",
        "/images/Cazasouq/Search Results.png",
        "/images/Cazasouq/Reset Password 2.png",
        "/images/Cazasouq/Order Details 1.png",
        "/images/Cazasouq/Order Details 2.png"
    ],

    Chillupwebdashboard: [
        "/images/Chillupwebdashboard/Products 1.png",
        "/images/Chillupwebdashboard/Transactions.png",
        "/images/Chillupwebdashboard/Follows & Reviews.png",
        "/images/Chillupwebdashboard/vendor register 2.png",
        "/images/Chillupwebdashboard/Create_ New Class 5 (Fixed Terms).png",
        "/images/Chillupwebdashboard/Account 3_My Profile.png",
        "/images/Chillupwebdashboard/Products 2 - View Product (Slots).png",
        "/images/Chillupwebdashboard/vendor register 1.png",
        "/images/Chillupwebdashboard/Account 4.png",
        "/images/Chillupwebdashboard/Create_ New Class 4 (Fixed Terms).png",
        "/images/Chillupwebdashboard/Customer List 1.png",
        "/images/Chillupwebdashboard/Account 6_Plan Super Chill.png",
        "/images/Chillupwebdashboard/Customer List 2.png",
        "/images/Chillupwebdashboard/Account2.png",
        "/images/Chillupwebdashboard/Create_ New Class 5 (Period).png",
        "/images/Chillupwebdashboard/Bookings 1.png",
        "/images/Chillupwebdashboard/Customer List_Free Plan.png",
        "/images/Chillupwebdashboard/Create_ New Class 4 (Period).png",
        "/images/Chillupwebdashboard/Create_ New Class 2.png",
        "/images/Chillupwebdashboard/Dashboard 3 - Notifications.png",
        "/images/Chillupwebdashboard/vendor thank you.png",
        "/images/Chillupwebdashboard/Create_ New Class 1.png",
        "/images/Chillupwebdashboard/vendor sign in.png",
        "/images/Chillupwebdashboard/Create_ New Class 6.png",
        "/images/Chillupwebdashboard/Create_ New Class 7.png",
        "/images/Chillupwebdashboard/Dashboard 2.png"
    ],

    ChillupBackend: [
        "/images/ChilllupBackend/Ads 2.png",
        "/images/ChilllupBackend/Notifications 1.png",
        "/images/ChilllupBackend/Ads 1.png",
        "/images/ChilllupBackend/Vendor Ads 2.png",
        "/images/ChilllupBackend/Vendor Ads 1.png",
        "/images/ChilllupBackend/AddSchoolRequest.png",
        "/images/ChilllupBackend/Feedback 2.png",
        "/images/ChilllupBackend/Feedback 1.png",
        "/images/ChilllupBackend/Vendors 1.png",
        "/images/ChilllupBackend/Trends 1.png",
        "/images/ChilllupBackend/Vendors 2.png",
        "/images/ChilllupBackend/Trends 2.png",
        "/images/ChilllupBackend/Trends 3.png",
        "/images/ChilllupBackend/Vendors 3.png",
        "/images/ChilllupBackend/Vendors 4.png",
        "/images/ChilllupBackend/Vendors 5.png",
        "/images/ChilllupBackend/Vendor Reviews 2.png",
        "/images/ChilllupBackend/Vendor Reviews 1.png",
    ],


    Calender: [
        "/images/Calender/Event.png",
        "/images/Calender/Event 2.png",
        "/images/Calender/Homepage.png"
    ],

    springringTeacherPortal: [
        "/images/springring TeacherPortal/Class Details.jpg",
        "/images/springring TeacherPortal/Class Registry - Students.jpg",
        "/images/springring TeacherPortal/Posts_ Event - Post to Users - Popup.png",
        "/images/springring TeacherPortal/Create New Post - Media Post - Step 2 Attachment & Alert - Post to Users.png",
        "/images/springring TeacherPortal/Posts_ Appointment (In-Person) View Results.png",
        "/images/springring TeacherPortal/Posts_ Images.png",
        "/images/springring TeacherPortal/Chat_Personal Chat Disabled.jpg",
        "/images/springring TeacherPortal/Posts_ Event.png",
        "/images/springring TeacherPortal/Whole School Details.jpg",
        "/images/springring TeacherPortal/Create New Post - Authorization - Step 2 Event.png",
        "/images/springring TeacherPortal/Posts_ Link.png",
        "/images/springring TeacherPortal/Posts_ Authorization View Results.png",
        "/images/springring TeacherPortal/Student Diary_Diary Board.jpg",
        "/images/springring TeacherPortal/Archived Boards - Classes.jpg",
        "/images/springring TeacherPortal/Edit Class.jpg",
        "/images/springring TeacherPortal/Class Registry - Students Profile.jpg",
        "/images/springring TeacherPortal/Create New Post - Appointment (Video) - Step 2.png",
        "/images/springring TeacherPortal/Profile & Settings.jpg",
        "/images/springring TeacherPortal/Create Class - Add Individual users.png",
        "/images/springring TeacherPortal/Create New Post - Media Post - Step 1 Boards.png",
        "/images/springring TeacherPortal/Chat 4.jpg",
        "/images/springring TeacherPortal/Create New Post - Media Post - Step 1 Users.png",
        "/images/springring TeacherPortal/Create New Post - Event - Step 1 Users.png",
        "/images/springring TeacherPortal/Chat 2.png",
        "/images/springring TeacherPortal/Posts_ Event - Post to Users.png",
        "/images/springring TeacherPortal/Archived board.jpg",
        "/images/springring TeacherPortal/Create New Post - Media Post - Step 2 Images & Alert.png",
        "/images/springring TeacherPortal/Chat 1.jpg",
        "/images/springring TeacherPortal/Posts_ Appointment (Video) View Results.png",
        "/images/springring TeacherPortal/All Updates_New comments.png",
        "/images/springring TeacherPortal/Calendar - Agenda.png",
        "/images/springring TeacherPortal/Student Diary_Diary Board - Viewer.jpg",
        "/images/springring TeacherPortal/Create New Post - Link Post - Step 1 Boards.png",
        "/images/springring TeacherPortal/TW Chat 4.jpg",
        "/images/springring TeacherPortal/Create New Post - Media Post - Step 2 Attachment & Alert.png",
        "/images/springring TeacherPortal/Profile & Settings - Chat and Office Hours - Enabled.png",
        "/images/springring TeacherPortal/Student Diary_View Post_Attachment.jpg",
        "/images/springring TeacherPortal/Class Registry - Students-1.jpg",
    ],

    Bahrain: [
        "/images/Bahrain/Homepage 2.png",
        "/images/Bahrain/DESKTOP Bahrain's Map.png",
        "/images/Bahrain/Desktop Homepage.png",
        "/images/Bahrain/DESKTOP My Itinerary.png",
        "/images/Bahrain/DESKTOP Journey (Culture) 1.png",
        "/images/Bahrain/DESKTOP Where to stay.png",
        "/images/Bahrain/DESKTOP Places to Eat 3.png",
        "/images/Bahrain/DESKTOP Journey (Taste).png",
        "/images/Bahrain/Things to do.png",
        "/images/Bahrain/DESKTOP Media - Images.png",
        "/images/Bahrain/DESKTOP Media - Press Releases.png",
        "/images/Bahrain/Explore more article 2.png",
        "/images/Bahrain/DESKTOP Where to stay Inside.png"
    ],

    SpringringAdminWeb: [
        "/images/SpringringAdminWeb/User Profile/Edit - Student & One Parent - Groups Dropdown.png",
        "/images/SpringringAdminWeb/User Profile/Edit - Admin.png",
        "/images/SpringringAdminWeb/Dashboard.png",
        "/images/SpringringAdminWeb/School Calendar - Month.png",
        "/images/SpringringAdminWeb/Manage Users - Add user Admin.png",
        "/images/SpringringAdminWeb/Manage Boards - Archives.png",
        "/images/SpringringAdminWeb/School Calendar - Agenda.png",
        "/images/SpringringAdminWeb/School Profile & Settings - School Profile.png",
        "/images/SpringringAdminWeb/User Profile - Student & Parents.png",
        "/images/SpringringAdminWeb/Import 2.png",
        "/images/SpringringAdminWeb/Create Board - Add Individual users.png",
        "/images/SpringringAdminWeb/Import 9 - Tags.png",
        "/images/SpringringAdminWeb/School Profile & Settings - Chat.png",
        "/images/SpringringAdminWeb/Manage Users - Add user Leader.png",
        "/images/SpringringAdminWeb/Create Group - Add Individual users - Loading.png",
        "/images/SpringringAdminWeb/Manage Boards - School Boards.png",
        "/images/SpringringAdminWeb/Manage Users - Add user.png",
        "/images/SpringringAdminWeb/Roll-over 11.png",
        "/images/SpringringAdminWeb/Roll-over 12.png",
        "/images/SpringringAdminWeb/Create Group.png",
        "/images/SpringringAdminWeb/Create Group - Add Individual users.png",
        "/images/SpringringAdminWeb/Saving behaviour 5.png",
        "/images/SpringringAdminWeb/School Contacts Edit.png",
        "/images/SpringringAdminWeb/Billing - Choose Plan.png",
        "/images/SpringringAdminWeb/Manage Groups.png",
        "/images/SpringringAdminWeb/Dashboard 2.png",
    ],

    Directory: [
        "/images/Directory/Site Contacts - View Group.png",
        "/images/Directory/Login.png",
        "/images/Directory/Groups Details - User Profile.png",
        "/images/Directory/Staff - User Selection.png",
        "/images/Directory/Groups Details - Group from user.png",
        "/images/Directory/Site Contacts.png",
        "/images/Directory/Groups.png",
        "/images/Directory/Groups Details.png",
        "/images/Directory/Staff.png",
        "/images/Directory/Site Contacts - Staff Profile.png",
        "/images/Directory/Staff - Staff Profile.png",
    ],

    ECA: [
        "/images/ECA/Cart.png",
        "/images/ECA/Homepage login.png",
        "/images/ECA/Confirmation.png",
        "/images/ECA/Checkout Paid.png",
        "/images/ECA/Checkout Free_ pop up.png",
        "/images/ECA/Checkout Free.png",
        "/images/ECA/Profile.png"
    ],

    AwalTerminal: [
        "/images/AwalTerminal/Option 1 - Tour@1x.png",
        "/images/AwalTerminal/General Aviation Form_1@1x.svg",
        "/images/AwalTerminal/Elite Form_2@1x.svg",
        "/images/AwalTerminal/Option 1 - Home@2x.png",
        "/images/AwalTerminal/Elite Form_4@1x.svg",
        "/images/AwalTerminal/Option 1 - Services_General Aviation@1x.png",
        "/images/AwalTerminal/Option 1 - Contact Us@1x.png",
        "/images/AwalTerminal/Option 1 - Our Story@1x.png",
        "/images/AwalTerminal/Elite Form_6@1x.svg",
        "/images/AwalTerminal/Payment 2@1x.svg",
        "/images/AwalTerminal/General Aviation Form_5@1x.svg",
        "/images/AwalTerminal/Elite Form_3@1x.svg",
        "/images/AwalTerminal/Elite Form_1@1x.svg",
        "/images/AwalTerminal/General Aviation Form_6@1x.svg",
        "/images/AwalTerminal/Payment 1@1x.svg",
        "/images/AwalTerminal/Elite Form_5@1x.svg",
        "/images/AwalTerminal/Elite Form_7@1x.svg",
    ],

    safercare: [
        "/images/safercare/image_original-1.jpg",
        "/images/safercare/image_original.jpg",
        "/images/safercare/image_original_2.jpg",
        "/images/safercare/image_original_4.jpg",
        "/images/safercare/image_original_6.jpg"
    ],

    ChillupMobile: [
        "/images/ChillupMobile/Home - School.png",
        "/images/ChillupMobile/Home - Review Notice.png",
        "/images/ChillupMobile/Kid2 Home - No Activity.png",
        "/images/ChillupMobile/Filters.png",
        "/images/ChillupMobile/Notifications-1.png",
        "/images/ChillupMobile/Review Order.png",
        "/images/ChillupMobile/Onboarding 4.png",
        "/images/ChillupMobile/Vendor Page - Info.png",
        "/images/ChillupMobile/Verify Mobile Number.png",
        "/images/ChillupMobile/School Info 3.png",
        "/images/ChillupMobile/Booked.png",
        "/images/ChillupMobile/School Info 1.png",
        "/images/ChillupMobile/Home - Activity.png",
        "/images/ChillupMobile/Vendors List.png",
        "/images/ChillupMobile/Kid2 Home - Settings Interests.png",
        "/images/ChillupMobile/Kid2 Home - Settings Colors.png",
        "/images/ChillupMobile/Create Event.png",
        "/images/ChillupMobile/Vendor Page - Profile.png",
        "/images/ChillupMobile/Splash.png",
        "/images/ChillupMobile/Create Activity Select End Date.png",
        "/images/ChillupMobile/Class details (Free).png",
        "/images/ChillupMobile/Notifications.png",
        "/images/ChillupMobile/Shopping Bag.png",
        "/images/ChillupMobile/Hearts.png",
        "/images/ChillupMobile/Profile.png",
        "/images/ChillupMobile/Create Activity Select From Date.png",
        "/images/ChillupMobile/Filters - One Option.png",
        "/images/ChillupMobile/Calendar - Agenda.png",
        "/images/ChillupMobile/Categories.png",
        "/images/ChillupMobile/Calendar - Month.png",
        "/images/ChillupMobile/Home - Settings.png",
        "/images/ChillupMobile/Complate your profile.png",
        "/images/ChillupMobile/Create Activity.png",
    ],

    chillupPublicWebsite: [
        "/images/ChillupPublicWebsite/Vendor.png",
        "/images/ChillupPublicWebsite/Parent.png",
        "/images/ChillupPublicWebsite/FAQ.png",
        "/images/ChillupPublicWebsite/Contact Us.png",
        "/images/ChillupPublicWebsite/About.png",
        "/images/ChillupPublicWebsite/Legal Info.png",
    ],

    naturallockbox: [
        "/images/naturallockbox/image_original-6.jpg",
        "/images/naturallockbox/.DS_Store",
        "/images/naturallockbox/image_original.JPG",
        "/images/naturallockbox/image_original_5.jpg",
        "/images/naturallockbox/image_original_4.JPG",
        "/images/naturallockbox/image_original_7.jpg",
        "/images/naturallockbox/image_original_3.JPG",
        "/images/naturallockbox/image_original_1.JPG",
    ],

    Admissions: [
        "/images/Admissions/EoI_Expired.png",
        "/images/Admissions/EoI Details.png",
        "/images/Admissions/Application 1.png",
        "/images/Admissions/Application 3.png",
        "/images/Admissions/Offer 1.png",
        "/images/Admissions/EoI Form 4.png",
        "/images/Admissions/EoI Form 5.png",
        "/images/Admissions/EoI Form 6.png"
    ],

    FRC: [
        "/images/PDPFRC/Login.png",
        "/images/PDPFRC/Parent View.png",
        "/images/PDPFRC/Analytics.png",
        "/images/PDPFRC/Create Unit - Topic.png",
        "/images/PDPFRC/Parent View - Subject Music.png",
        "/images/PDPFRC/Parent View - Assessment Modes.png"
    ],

    PDP: [
        "/images/PDP/Teacher Leader_Pedagogical focus.png",
        "/images/PDP/Teacher Leader_Strategic Priorities - Future Ready Curriculum.png",
        "/images/PDP/Teacher Leader_Leadership Focus.png",
        "/images/PDP/Teacher Leader_Home.png",
        "/images/PDP/Teacher Leader_Self Evaluation.png",
    ],

    SPEA: [
        "/images/Spea/Investors - School View 4.png",
        "/images/Spea/Parent 08.png",
        "/images/Spea/Investors - School View 1.png",
        "/images/Spea/Parent 03.png",
        "/images/Spea/Forecast.png",
        "/images/Spea/Parent 02.png",
        "/images/Spea/Parent 01.png",
        "/images/Spea/Parent 06.png",
    ],

};

export default ProjectGalleries;
