export const TESTIMONIALS = [
    {
        name: "Jo Infinity Fly",
        location: "UK",
        text: "I would highly recommend Umer. He is a pleasure to work with and highly skilled. He has addressed countless bugs and fixes that had crept into my system. He has since added new features and developed my platform into a reliable and stable product. I would not hesitate to re-hire him on future contracts.",
        image:"/images/screenshot/jo.png",
        isImage:true,
    },
    {
        name: "Ramla Hassan",
        location: "Australia",
        text: "I've had the chance to work closely with Umer during the development of portals for Safr Care... One of the smartest developers I've met! I highly recommend him.",
        image:"/images/screenshot/ramla.png",
        isImage:true,
    },
    {
        name: "Tripsholi",
        location: "Spain",
        text: "Umer is skilled, reliable, and always focused on getting the job done right. His attention to detail and code quality are impressive. Highly recommended.",
        image:"/images/screenshot/tripsholi.png",
        isImage:true,
    },
    {
        name: "Ahmed Burkhi",
        location: "Germany",
        text: "If you are looking for a website job done. Umer A. is your person to work with. Great knowledge with good skill in design and a professional in coding. Highly recommended.",
        image:"/images/screenshot/ahmed.png",
        isImage:true,
    },
    {
        name: "Jawad Sadiq",
        location: "Bahrain",
        text: "Umer's expertise and work ethic were outstanding. It would be a privilege to work with him again, and I would highly recommend them for any Vue.js development projects.",
        image:"/images/screenshot/jawad.png",
        isImage:true,
    },
    {
        name: "Mohammad Ashoor",
        location: "Dubai, UAE",
        text: "Umer performed an excellent job developing the required website. The communication was excellent, and the talents were exceptional. We will collaborate with Umer on any future ventures.",
        image:"/images/screenshot/ashoor.png",
        isImage:true,
    },
    {
        name: "Salacious Styles",
        location: "India",
        text: "From the start of the project, through to completion, Umer supported us and exceeded our expectations in every way... He's reliable, professional and easy to work with.",
        image:"/images/screenshot/salcious.png",
        isImage:true,
    },
    {
        name: "Ramiro Martinez",
        location: "Argentina",
        text: "Umer did an excellent job on this project with Laravel and Vue. He took a complex requirement and solved it perfectly with very good quality. Communication was excellent.",
        image:"/images/screenshot/ramiro.png",
        isImage:true,
    },

    {
        name: "Itzone Graz",
        location: "Austria",
        text: "Umer understood our needs quickly and delivered results ahead of time. We truly appreciated his clarity and efficiency, would absolutely work with him again.",
        image:"/images/screenshot/zone.png",
        isImage:true,

    },

    {
        name: "Ruman Munir",
        location: "Canada",
        text: "The job was done promptly. Umer has done some additional things in my app which I haven't in my mind. He is amazing and acts as a professional, and delivered quality work.",
        image:"/images/screenshot/ruman.png",
        isImage:true,
    },

    {
        name: "Sa Pl",
        location: "United States",
        text: "Umer was incredibly reliable and delivered everything on time. He handled complex logic smoothly and helped improve performance throughout the app. I appreciated his professional communication and will definitely be working with him again.",
        image:"",
        isImage:false,
    },
    {
        name: "Greg Ichshenko",
        location: "Canada",
        text: "Working with Umer was a great experience. He was efficient, responsive, and brought smart solutions to every problem we encountered. Highly recommended for any full-stack work!",
        image:"/images/screenshot/grey.png",
        isImage:true,
    },
    {
        name: "Jeremy Buettner",
        location: "United States",
        text: "Umer is a talented developer who quickly understood our needs and delivered quality results. His technical knowledge and positive attitude made the collaboration seamless and productive.",
        image:"/images/screenshot/jeremy.png",
        isImage:true,
    },
    {
        name: "Tae Geun Kim",
        location: "South Korea",
        text: "Umer provided excellent service and communicated clearly throughout the project. His skills in frontend and backend development are top-notch. I look forward to future projects with him.",
        image:"",
        isImage:false,
    },
    {
        name: "Mateo Garcia",
        location: "Argentina",
        text: "Very satisfied with Umer’s work. He was thorough, detail-oriented, and very responsive to feedback. Great developer who adds real value to a project.",
        image:"",
        isImage:false,
    },
    {
        name: "Philip Couboura",
        location: "Burkina Faso",
        text: "Umer did a fantastic job and exceeded expectations. He’s a strong communicator and was able to implement all our requirements with precision and care. Would gladly work with him again.",
        image:"",
        isImage:false,
    },

    {
        name: "Codeforisl",
        location: "Pakistan",
        text: "The best developer I’ve ever worked with. Umer delivered the project even before the deadline and added valuable features we hadn’t thought of. Truly exceptional.",
        image:"",
        isImage:false,
    },
    {
        name: "Conor Wilson",
        location: "Ireland",
        text: "Great communication and design recommendations. Umer always welcomes feedback and iterates quickly. We've worked multiple times and I’ll keep coming back.",
        image:"/images/screenshot/conor.png",
        isImage:true,
    },
    {
        name: "Vikas Rajput",
        location: "India",
        text: "Thank you for creating a wonderful website. Umer’s work is exceptional, and his support has been greatly appreciated.",
        image:"",
        isImage:false,
    },
    {
        name: "KJ World",
        location: "Australia",
        text: "He completed the work quickly and with high quality. Very professional and responsive. Would love to work again.",
        image:"",
        isImage:false,
    },
    {
        name: "Svenn Lieb",
        location: "South Africa",
        text: "Very helpful and proactive. Umer was always available for revisions and took initiative to enhance the project. I will definitely hire him again.",
        image:"",
        isImage:false,
    },
    {
        name: "Kasuner The Bet",
        location: "Denmark",
        text: "Open, honest, and easy to communicate with. Umer helped refine the product and added thoughtful suggestions for improvements. Highly satisfying experience.",
        image:"",
        isImage:false,
    },
    {
        name: "Jalil Hamdani",
        location: "Pakistan",
        text: "Sophisticated and solution-oriented services. Highly recommended for the ones looking for professional website development. Reliable, timely, and collaborative.",
        image:"/images/screenshot/jalil.png",
        isImage:true,
    },
];
